### ISSUE TITLE
Add a config item for disallowing non-craftable weapons as currency

### ISSUE THREAD

**Issue by Bonfire** [idinium96/tf2autobot#127]
**Is your feature request related to a problem? Please describe.**
Users are able to trade non-craftable weapons to the bot at a price of 0.05 refined. Due to these items not being craftable, they cannot be smelted into scrap metal, forcing the user to have to re-sell the items (even though they did not have a listing for the items). This results in classified listing slots and backpack slots being taken up, without any recourse but to re-sell the items.

**Describe the feature you'd like**
I propose a new config item (`DISABLE_NONCRAFT_AS_CURRENCY`) for the bot that will allow the user to enable or disable the accepting of non-craftable weapons as currency. 

This config item would be separate from `DISABLE_CRAFTWEAPON_AS_CURRENCY`, but `DISABLE_CRAFTWEAPON_AS_CURRENCY` would supersede this config item. As an example, if `DISABLE_CRAFTWEAPON_AS_CURRENCY` is set to `true`, then non-craftable weapons would not be accepted as currency either. If `DISABLE_CRAFTWEAPON_AS_CURRENCY` is set to `false`, then craftable weapons would be accepted, but the user would still have to option to not accept non-craftable weapons (through this new config item).

**Describe alternatives you've considered**
The only alternative I can think of is to not accept weapons as currency in general. Besides that, the bot must re-list non-craftable weapons if it would like to get rid of them.

**Additional context**
None

**Comment by idinium96** [comment]
might add this in v1.7.1. Thanks for the suggestion, but "the bot must re-list non-craftable weapons if it would like to get rid of them.", hurmm might be in the auto-add invalid_items I guess.

**Comment by idinium96** [comment]
complicated.
