### ISSUE TITLE
Don't update keys max,min with update all=true if autokeys is on.

### ISSUE THREAD

**Issue by joekiller** [idinium96/tf2autobot#131]
**Is your feature request related to a problem? Please describe.**
When I'm trying to just adjust the scale of total items I'm banking it would be good if the update all=true didn't override my autokeys settings.

**Describe the feature you'd like**
update all=true by default doesn't make changes to 5021;6 (key) sku if auto keys is turned on.

**Describe alternatives you've considered**
Currently I just manually set back whatever I change ie, look it up: `!get sku=5021;6` and then `!update sku=5021;6&max=42`

**Additional context**
Perhaps a config option if "ALL_OVERRIDES_AUTOKEYS" with a default to "false"

**Comment by idinium96** [comment]
Hurmmm... I don't want too many variables tbh.
There's already an items grouping feature added.

you can do `!update all=true&group=all`, then update group for key, so then when you want to update all items again, just send `!update all=true&withgroup=all&[parameters to update]`.

**Comment by joekiller** [comment]
The way I see it auto keys is a feature of tf2autobot. Since auto keys is a differentiating feature, I see it's functionality trumping the pricelist. ie, As a user i expect the tf2autobot to remain true to its features even if the user runs dumb commands.

As for a config option, I see that as an escape hatch out of the top level features. Typically people keep the suggested defaults.

**Comment by idinium96** [comment]
I see. I agree with you. I might add some check [here](https://github.com/idinium96/tf2autobot/blob/master/src/classes/Commands.ts#L1359) if Autokeys enabled and exist in pricelist, then keys entry will be removed from `newPricelist`.

**Comment by joekiller** [comment]
Hi tested this on the latest this on 6c558ddc05b8bfa166427840e85ecde11138948a and it worked fine. Thanks!

**Comment by idinium96** [comment]
glad to hear that! 👍
