### ISSUE TITLE
Provide further information to admin/trade partner on Error Result 15 (Full Backpack)

### ISSUE THREAD

**Issue by Bonfire** [idinium96/tf2autobot#134]
**Is your feature request related to a problem? Please describe.**
Currently, when a trade offer results in Error 15 ("I don't, or the trade partner don't, have space for more items."), the admin is provided no information on where the issue lies, or if the issue is caused by Steam.

**Describe the feature you'd like**
I propose an enhancement that would provide the admin and trade partner with a summary of each person's backpack slots. For example, if the bot attempts to accept the trade offer, but the trade is declined due to either party not having enough backpack slots, the bot should provide each user's current backpack slots, and maximum backpack slots. This would both inform the user by prompting them to free up backpack slots (if they are full), and inform the admin by helping them further investigate the issue (if the bot has no more slots).

An example updated message sent to the trade partner when this error occurs:
```
I don't, or you don't, have space for more items.
📦 My backpack: 700 / 1300 slots used
📦 Your backpack: 550 / 600 slots used
```

An example updated discord message sent to the admin when this occurs:
```
Something Wrong
I don't, or the trade partner don't, have space for more items. Please take a look.
📦 My backpack: 700 / 1300 slots used
📦 Partner's backpack: 550 / 600 slots used
<DATE AND TIME HERE>
```

**Describe alternatives you've considered**
There is no alternative to this issue. For the admin to investigate why this issue occurs, they have to fully update both the bot and the trade partner's backpacks, to see who is out of space. Sometimes this issue occurs not because anyone is out of slots, but because of issues on Steam's end. This would show the admin that there are no _actual_ issues, and instead the issue lies on Steam's side of things.

**Additional context**
This feature could be further fleshed out by providing each party with a summary of how many items the trade would take up. 

An example can be seen below:
```
I don't, or you don't, have space for more items.
📦 My backpack: 700 / 1300 slots used
📦 Your backpack: 550 / 600 slots used
⬅️ I would receive 2 item(s) -> 702 / 1300 slots
➡️ You would receive 86 item(s) -> 636 / 600 slots
```

---

Also, if this feature is modified, I think that the wording on the messages should be updated to be more grammatically correct. 

Here is how I would modify the current verbiage:
- `I don't, or the trade partner don't, have space for more items. Please take a look.` **->** `Either I, or the trade partner, do not have enough backpack space to complete this trade`
- `I don't, or you don't, have space for more items` **->** `Either you or I don't have enough backpack slots to complete this trade`

**The above wording changes would be accompanied by the example messages I provided above. So instead of saying "I don't or you don't...", it would say "Either I, or the trade partner..." and would provide the error summary.**

**Comment by idinium96** [comment]
Alright. I will have a look into this, or maybe you can add it, but it will be in v1.7.2 as I am merging v1.7.1 right now.

**Comment by Bonfire** [comment]
> Alright. I will have a look into this, or maybe you can add it, but it will be in v1.7.2 as I am merging v1.7.1 right now.

Awesome! Glad to hear it. I just made some more information to the issue to help out whoever takes on this task.
