### ISSUE TITLE
Parameter "withoutgroup"

### ISSUE THREAD

**Issue by Dex-Spirit** [idinium96/tf2autobot#140]
**Describe the feature you'd like**
Parameter `withoutgroup` for _!update_ command that will update all items except specified group.
For example:
_!update all=true&withoutgroup=weapons_ - will update all items except items that has `"group": weapons`

**Comment by Bonfire** [comment]
I think that this parameter and other "group"-related suggestions should be folded up into a larger `!groups` command.
