### ISSUE TITLE
Add key/metal stock parameter to listing notes

### ISSUE THREAD

**Issue by Bonfire** [idinium96/tf2autobot#141]
**Is your feature request related to a problem? Please describe.**
There are no active issues/problems related to this enhancement request.

However, it is always a pain when attempting to trade with a bot and the bot does not have enough keys or pure to complete a trade. You add the bot, set up the trade, only to find out that you can't even perform the trade. To prevent something like this from happening, and to provide potential trade partners with more information about the bot (which is always a good thing!), I propose the below enhancement.

**Describe the feature you'd like**
I propose a new parameter for listing notes that will display the bot's current stock of keys and pure metal. Such parameters could be structured like so: `%keyStock%` and `%metalStock` **or** as a single parameter like `%pureStock%`. These parameters would be replaced with the bot's current number of keys, and the bot's current count of metal. For the metal count, this could be done in the "refined format", such as `323.66` (for Three Hundred and Twenty-Three Refined Metal and Two Reclaimed Metal).

* If the `%keyStock%` and `%metalStock` approach is taken, `%keyStock%` would be replaced with the bot's current key count, and `%metalStock` would be replaced with the bot's current metal count. An example being `%keyStock%, %metalStock` --> `3 keys, 799.44 refs`.
* If the `%pureStock%` approach is taken, this could simply re-use code from the `pureCommand()`. An example being `%pureStock%` --> `3 keys and 799.44 refs`.

Either approach can be taken. The first would provide more customization to the user, whereas the second approach seems to be more intuitive and simpler.

**Describe alternatives you've considered**
There are no alternatives to this, as this is a request for a new feature.

**Additional context**
An example of how a bot's listing note could be structured after these parameters are replaced is shown below:

**After Replacement (with `%keyStock%` and `%metalStock%`):**
![image](https://user-images.githubusercontent.com/5704760/99285658-d77a5c00-2805-11eb-99c4-16f868c7a76f.png)

**After Replacement (with `%pureStock%`):**
![image](https://user-images.githubusercontent.com/5704760/99286042-540d3a80-2806-11eb-8d37-c5f5e406b58c.png)

**Comment by idinium96** [comment]
No. I've done this before. You're not allowed to update listing notes if you're changing something other than prices/ items stock (not pure stock).

**Comment by idinium96** [comment]
Discord chat: https://discordapp.com/channels/445215464386330644/445228694231973888/709051722512990312
