### ISSUE TITLE
"!options" command

### ISSUE THREAD

**Issue by Dex-Spirit** [idinium96/tf2autobot#168]
**Describe the feature you'd like**
New command called `!settings` that will show your variables settings.
![image](https://user-images.githubusercontent.com/61100980/100108994-0f237c80-2e74-11eb-87aa-c3d61b8319e9.png)

**Comment by idinium96** [comment]
Will do like this (v2):
![image](https://user-images.githubusercontent.com/47635037/100214685-22554b80-2f4b-11eb-83a5-50130b6ca3c6.png)
