### ISSUE TITLE
Add current stock and maximum stock to trade summary

### ISSUE THREAD

**Issue by Bonfire** [idinium96/tf2autobot#170]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the feature you'd like**
I propose an addition to the current trade summary feature that displays the current stock and maximum stock of items bought and sold that are in the pricelist. For example, the bot has 10 keys (and has it's maximum number of keys set to 10). Then the bot sells 6 keys. In the trade summary, the bot would display a "4 / 10" next to keys in the item list, showing the admin that it currently has 4 out of a maximum of 10 keys

**Describe alternatives you've considered**
Find your current stock and max stock by running the `!get` command or by checking the bot's listing for a specific item.

**Additional context**
No additional context

**Comment by idinium96** [comment]
This sounds easy, but it's complicated, so I don't know if this will get implemented or not.
