### ISSUE TITLE
!config command crashes 

### ISSUE THREAD

**Issue by christianpug** [idinium96/tf2autobot#180]
**Describe the bug**

**To Reproduce**

1. goto your steam chat and goto your bot
2. .type !config manualReview.enable=false
3. it crashes

**Expected behavior**
> 0|Pootis_Bot  | TypeError: Cannot read property 'exceptionValue' of undefined
0|Pootis_Bot  |     at Object.updateOptionsCommand (/root/tf2autobot/dist/classes/Commands/optionsCommands.js:94:46)
0|Pootis_Bot  |     at Commands.processMessage (/root/tf2autobot/dist/classes/Commands/Commands.js:209:30)
0|Pootis_Bot  |     at MyHandler.onMessage (/root/tf2autobot/dist/classes/MyHandler/MyHandler.js:291:23)
0|Pootis_Bot  |     at Bot.onMessage (/root/tf2autobot/dist/classes/Bot.js:543:22)
0|Pootis_Bot  |     at Immediate.<anonymous> (/root/tf2autobot/dist/classes/Bot.js:163:21)
0|Pootis_Bot  |     at processImmediate (node:internal/timers:463:21)
0|Pootis_Bot  | 2020-11-29 16:40:31 error: TF2Autobot crashed! Please create an issue with the following log:
0|Pootis_Bot  | package.version: 2.0.1; node: v15.2.1 linux x64}
0|Pootis_Bot  | Stack trace:
0|Pootis_Bot  | TypeError: Cannot read property 'exceptionValue' of undefined
0|Pootis_Bot  |     at Object.updateOptionsCommand (/root/tf2autobot/dist/classes/Commands/optionsCommands.js:94:46)
0|Pootis_Bot  |     at Commands.processMessage (/root/tf2autobot/dist/classes/Commands/Commands.js:209:30)
0|Pootis_Bot  |     at MyHandler.onMessage (/root/tf2autobot/dist/classes/MyHandler/MyHandler.js:291:23)
0|Pootis_Bot  |     at Bot.onMessage (/root/tf2autobot/dist/classes/Bot.js:543:22)
0|Pootis_Bot  |     at Immediate.<anonymous> (/root/tf2autobot/dist/classes/Bot.js:163:21)
0|Pootis_Bot  |     at processImmediate (node:internal/timers:463:21)

**Screenshots and logs**
![screenshot](https://user-images.githubusercontent.com/37443483/100548120-ae5fbf80-3238-11eb-947e-6aceff118fa2.PNG)
![screenshot2](https://user-images.githubusercontent.com/37443483/100548121-ae5fbf80-3238-11eb-8b1e-fcf56ae32510.PNG)

**Additional context**

Version: 2.0.1

**Comment by joekiller** [comment]
Looking at this some @idinium96 I wonder why https://github.com/idinium96/tf2autobot/blob/master/src/classes/Commands/optionsCommands.ts#L36-L122 is necessary. Shouldn't the validator (here https://github.com/idinium96/tf2autobot/blob/master/src/classes/Commands/optionsCommands.ts#L130) catch any issues?

**Comment by joekiller** [comment]
If we want extra validation it would be safer to do that after the schema verification because then the options object is valid.

**Comment by idinium96** [comment]
> Looking at this some @idinium96 I wonder why https://github.com/idinium96/tf2autobot/blob/master/src/classes/Commands/optionsCommands.ts#L36-L122 is necessary. Shouldn't the validator (here https://github.com/idinium96/tf2autobot/blob/master/src/classes/Commands/optionsCommands.ts#L130) catch any issues?

You will get "bla bla bla is not type of string array."
And also, if you change the custom game name, it will not trigger to change the game name immediately.

**Comment by joekiller** [comment]
You could move all that highlighted stuff after the schema validation and
it should work fine.

Sent via mobile

**Comment by idinium96** [comment]
oh right. Will do that. Thanks 👍

**Comment by idinium96** [comment]
but what about changing string into array? Will it also work?

**Comment by idinium96** [comment]
fixed in the latest v2.0.2.
Closing.
