### ISSUE TITLE
Bot fails to combine enough metal.

### ISSUE THREAD

**Issue by Dex-Spirit** [idinium96/tf2autobot#189]
**Describe the bug**
Bot spams failed combining job on every start / accepted trade and in result it didn't combine enough metal.
Metal stock is always at `9 Reclaimed and 2 Scrap` or `9 Scrap and 0 Reclaimed`

**To Reproduce**

1. Wait for combining job (on start / accepted trade).
2. Check the logs & metal stock.

**Expected behavior**
Craft enough metal to have enough change for the trade.

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/61100980/100752189-f45f8380-33f0-11eb-943c-983ac084d582.png)

**Additional context**

Version: 
v2.0.4

**Comment by idinium96** [comment]
Fixed in v2.1.0 (https://github.com/idinium96/tf2autobot/releases/tag/v2.1.0)
Thanks for creating an issue.
