### ISSUE TITLE
Fix displaying prices when item pricing is disabled

### ISSUE THREAD

**Issue by luigia** [idinium96/tf2autobot#191]
**Describe the bug**
When checking the price (`!price <name>`) of a disabled listing, the bot replies saying that it's not selling the item, followed with a message saying that it's selling the item along with their prices.

**To Reproduce**

1. Lookup the name of an item that is currently disabled with `!price <name>`
2. Observe result

**Expected behavior**
A check to see if the item listing is enabled. It should not say that it's selling the item to prevent confusion.

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/4554967/100824636-8cc32b80-3424-11eb-8064-2498c6f4b1bb.png)

Version: TF2Autobot@v2.1.0

**Comment by idinium96** [comment]
Thanks for reporting. Will be fixed on v2.1.1.
