### ISSUE TITLE
Let !config trigger autokeys updates

### ISSUE THREAD

**Issue by joekiller** [idinium96/tf2autobot#205]
Feature: When autokeys settings get updated have the bot evaluate if it needs to turn autokeys on or off. Right now I think a trade has to take place to trigger a change.

**Comment by idinium96** [comment]
Yes, correct. The most convenient way because most pure changes occur after a trade.

**Comment by idinium96** [comment]
also, there's also `!refreshautokeys` command, so I think this is not needed.

**Comment by joekiller** [comment]
I think a low frequency trader would appreciate this more esp if their bot needs to be adjusted. For example they are getting no trades because their listings aren't active due to low ref or keys or not quite enough ref to key ratio bc it's changing so much. They'd adjust their options and expect the bot to react to that. Ie as a user I want autokeys to adjust and make buy orders if I adjust the settings. I don't want to have to know another command if I just made it what I want.

I can work on this fwiw

**Comment by idinium96** [comment]
I see. so maybe like `if (params.autokeys !== undefined) autokeys.check()` right?
Sure you can assign yourself for this.

**Comment by joekiller** [comment]
Yup I'll works on it

Sent via mobile
