### ISSUE TITLE
Typo in steam chat report.

### ISSUE THREAD

**Issue by nedim387** [idinium96/tf2autobot#209]
**Describe the bug**
A typo in steam chat report summary. It spells "Killstreker" but should actually spell "Killstreaker":

 ✅Summary• Asked: 29 keys, 8.55 ref (Strange Professional Killstreak Australium Knife)• Offered: 29 keys, 8.55 ref (Mann Co. Supply Crate Key x29, Refined Metal x8, Reclaimed Metal, Scrap Metal x2)🔶_HIGH_VALUE_ITEMS:- Strange Professional Killstreak Australium Knife🔥 **Killstreker**: Flames✨ Sheen: Agonizing Emerald🔑 Key rate: 61.44/61.55 ref (prices.tf) | Autokeys: ✅ (buying)💰 Pure stock: 92 keys, 762.22 refs (758 ref, 10 rec, 8 scrap) 🎒 Total items: 2228/2500⏱ Time taken: 2 minutes

**Expected behavior**
It should spell Killstreaker instead of Killstreker

Version: 
2.1.2

**Comment by idinium96** [comment]
lol I am fixing it @Bonfire

**Comment by idinium96** [comment]
but it's ok you can take it
