### ISSUE TITLE
"STEAM_ACCOUNT_NAME" missing

### ISSUE THREAD

**Issue by Acornhut** [idinium96/tf2autobot#26]
I typed in my steam account name, along with all my other info in template.env yet when I type "node dist/app.js" i get two errors:

-tf2autobot failed to start properly, this is most likely a temporary error. See the log: 
  package.version: 1.1.5; node: v12.16.3 win32 x64}

-Error: Missing required environment variable "STEAM_ACCOUNT_NAME"

If anyone has an answer I would be happy to read it.
![Steam_account_name](https://user-images.githubusercontent.com/65208262/86982393-1c56fd80-c157-11ea-8309-181f2a7dd816.PNG)

**Comment by DexGunner** [comment]
> I typed in my steam account name, along with all my other info in template.env yet when I type "node dist/app.js" i get two errors:

> -Error: Missing required environment variable "STEAM_ACCOUNT_NAME"

Rename filled with information file “template.env” to “.env”

**Comment by Acornhut** [comment]
Thanks, but that hasn't worked. I got the same message again

**Comment by Dex-Spirit** [comment]
> I just tried it but that hasn't worked. I got the same message again

Have you entered the username you use when entering your Steam account?

**Comment by Acornhut** [comment]
yes

**Comment by Acornhut** [comment]
![Steam_account_name (1)](https://user-images.githubusercontent.com/65208262/86985550-7fe52900-c15f-11ea-8eb8-712ad8dd3552.PNG)
is this what you asked me to do?

**Comment by Dex-Spirit** [comment]
> ![Steam_account_name (1)](https://user-images.githubusercontent.com/65208262/86985550-7fe52900-c15f-11ea-8eb8-712ad8dd3552.PNG)
> is this what you asked me to do?

This file should be added in bot’s folder, you created folder called “.env” with file “.env”. Move file to the “tf2autobot-master” folder.

**Comment by Acornhut** [comment]
That worked, and thanks for that but there's a new issue
![Steam_account_name (2)](https://user-images.githubusercontent.com/65208262/86986108-d99a2300-c160-11ea-8c83-b387d423ad29.PNG)

**Comment by Dex-Spirit** [comment]
Your Steam account(bot’s account) should be unrestricted to use Steam API. 
https://support.steampowered.com/kb_article.php?ref=3330-iagk-7663

**Comment by Acornhut** [comment]
I just removed the restriction today but it says i need to have some games in my library to access my Steam API so ill get to it
Thanks and ill let you know if I hit a dead-end again.

**Comment by idinium96** [comment]
any other common errors can be found here: https://github.com/idinium96/tf2autobot/wiki/g.-Errors
