### ISSUE TITLE
Bot Stopped working after windows update

### ISSUE THREAD

**Issue by DirtyDrep** [idinium96/tf2autobot#92]
**Describe the bug**

**To Reproduce**

1. Updated windows

**Expected behavior**

**Screenshots and logs**
  Log files are located at `~/tf2autobot/logs`. There are three log files:
 0|tf2autobot  | 2020-10-16 21:32:58 info: Starting bot...
0|tf2autobot  | 2020-10-16 21:32:58 debug: Calling onRun
0|tf2autobot  | SyntaxError: Unexpected token  in JSON at position 0
0|tf2autobot  |     at JSON.parse (<anonymous>)
0|tf2autobot  |     at C:\Users\optim\Desktop\tf2autobot\dist\lib\files.js:29:31
0|tf2autobot  |     at C:\Users\optim\Desktop\tf2autobot\node_modules\graceful-fs\graceful-fs.js:123:16
0|tf2autobot  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
0|tf2autobot  | 2020-10-16 21:32:58 error: tf2autobot failed to start properly, this is most likely a temporary error. See the log:
0|tf2autobot  | package.version: 1.5.3; node: v12.18.4 win32 x64}
0|tf2autobot  | Stack trace:
0|tf2autobot  | SyntaxError: Unexpected token  in JSON at position 0
0|tf2autobot  |     at JSON.parse (<anonymous>)
0|tf2autobot  |     at C:\Users\optim\Desktop\tf2autobot\dist\lib\files.js:29:31
0|tf2autobot  |     at C:\Users\optim\Desktop\tf2autobot\node_modules\graceful-fs\graceful-fs.js:123:16
0|tf2autobot  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
0|tf2autobot  | 2020-10-16 21:32:58 debug: Shutdown has been initialized, stopping... {"err":{}}
0|tf2autobot  | 2020-10-16 21:32:58 debug: Handler finished cleaning up
0|tf2autobot  | 2020-10-16 21:32:58 debug: Waiting for files to be saved
0|tf2autobot  | 2020-10-16 21:32:58 debug: Done waiting for files
0|tf2autobot  | 2020-10-16 21:32:58 warn: Exiting...
PM2           | App [tf2autobot:0] exited with code [1] via signal [SIGINT]
PM2           | App [tf2autobot:0] starting in -fork mode-
PM2           | App [tf2autobot:0] online
**Additional context**

Version:  1.5.3

**Comment by idinium96** [comment]
If Windows just automatically restart your PC without properly shutdown your bot, this problem could occur because your `polldata.json` or `pricelist.json` file is corrupted.
https://github.com/idinium96/tf2autobot/wiki/g.-Errors#unexpected-token-in-json

Try deleting your `polldata.json` file found in the `~\tf2autobot\files\YourBotSteamUsername\polldata.json`

**Comment by idinium96** [comment]
I guess this problem has been solved.
